name: Terraform

on: push

jobs: 
  Infra: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout apiVersion
        uses: actions/checkout@v3
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2 
        with: 
          terraform_version: 1.1.9 
      - name: T init 
        env: 
          AWS_ACCESS_KEY_ID: ${{ secret.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secret.AWS_SECRET_KEY}}
        run: | 
          ls 
      - name: See Output 
        id: Output
        run: | 
          ls
          terraform -version 
      
          
