name: Terraform

on: push

jobs: 
  Infra: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout apiVersion
        uses: actions/checkout@v3
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2 
        with: 
          terraform_version: 1.1.9 
      - name: T init 
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}
        run: | 
          
          terraform -chdir=terraform/ init 
      - name: See Output 
        id: Output
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}
        run: | 
          
          terraform -chdir=terraform/ plan 
      - name: Terraform Apply
        id: apply
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY}}
        run: | 
          
          terraform apply -chdir=terraform/ --auto-approve
          
      
          
